os:
  
  - linux

language:
  
  - python

python:

  - "3.8"

before_install:
  
  - sudo apt-get update -q
  - sudo apt-get install -y -q wget build-essential g++ cmake libz-dev libcurl4-openssl-dev libssl-dev libbz2-dev liblzma-dev libncurses5-dev bedtools
  - sudo apt-get clean
  - ./configure

install:
  
  - python setup.py install

script:

  - bash test/test.sh

notifications:

  email:

    recipients:

      - davidebolognini7@gmail.com

    on_success: always
    on_failure: always